name = "dataflow-api"
main = "src/index.ts"
compatibility_date = "2024-02-09"
compatibility_flags = ["nodejs_compat"]
account_id = "985d023768a24497cde522d6654877b2"

[[d1_databases]]
binding = "DB"
database_name = "dataflow-db"
database_id = "df76ff92-4387-48dd-ba50-7299c4997342"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "dataflow-datasets"

[[kv_namespaces]]
binding = "CACHE"
id = "88fb337b933f460f9ebbab5b534780f8"

[ai]
binding = "AI"

[vars]
ENVIRONMENT = "production"
